[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[features]
default = [ "thread-local-executor" ]
thread-local-executor = []

[dependencies]
futures = "0.3.15"
uuid = { version = "0.8.2", features = ["v4"] }
